### ISSUE TITLE
未實作狀態記錄

### ISSUE THREAD

**Issue by littleCube2019** [littleCube2019/Duel_game#10]
指已實作供使用的模組端
還未實作server.js的執行端，跟main.html的呈現端

1. 狂暴(rage)
每回合可以攻擊兩次
2. 不死(undeath)
每次死亡時會以最大生命值50%滿血復活
並且不死效果仍存在，直到最大生命值為1死亡時才正式死亡
每次復活最大攻擊力-1，直到最大攻擊力為1時不扣攻擊力

3. 精靈相關流程還未加入

4. 精靈捨身狀態(sprite_sacrifice)
優先承受我方傷害

5. 精靈蝸居狀態(sprite_snail)
不能選取 攻擊 行為

6. 吸血(suckBlood)
對敵人造成的傷害會回復50%至自身

7. 祈禱(canPray)
一個新增行為
(解完神之眷顧後可回血，往後祈禱會為我方單體回復2點HP)

8. 赤色祝福(canRedBless)
攻擊力+2 三回合 

9. 靛色祝福(canBlueBless)
防禦力+2 三回合

10. 第二道具欄(secondItem)

11. 小偷(thief)
攻擊時可以有25%機率獲得對方道具
若道具滿了，則可以選擇要留下原道具或對方道具

future:
精靈應被視作與玩家相同之物件

**Comment by brad1024** [comment]
> 指已實作供使用的模組端
> 還未實作server.js的執行端，跟main.html的呈現端
> 
> 1. 狂暴(rage)
>    每回合可以攻擊兩次
> 2. 不死(undeath)
>    每次死亡時會以最大生命值50%滿血復活
>    並且不死效果仍存在，直到最大生命值為1死亡時才正式死亡
>    每次復活最大攻擊力-1，直到最大攻擊力為1時不扣攻擊力
> 3. 精靈相關流程還未加入
> 4. 精靈捨身狀態(sprite_sacrifice)
>    優先承受我方傷害
> 5. 精靈蝸居狀態(sprite_snail)
>    不能選取 攻擊 行為
> 6. 吸血(suckBlood)
>    對敵人造成的普通攻擊傷害會回復50%至自身
> 7. 祈禱(canPray)
>    一個新增行為
>    (解完神之眷顧後可回血，往後祈禱會為我方單體回復2點HP)
> 8. 赤色祝福(canRedBless)
>    攻擊力+2 三回合
> 9. 靛色祝福(canBlueBless)
>    防禦力+2 三回合
> 10. 第二道具欄(secondItem)
> 11. 小偷(thief)
>     攻擊時可以有25%機率獲得對方道具
>     若道具滿了，則可以選擇要留下原道具或對方道具
> 
> future:
> 精靈應被視作與玩家相同之物件
