### ISSUE TITLE
Next step(Before Chinese New Year)

### ISSUE THREAD

**Issue by littleCube2019** [littleCube2019/Duel_game#6]
# 實作功能
* 道具功能
* 選卡 (含顯示)
* 放棄任務    **(完成待brad確認)**
* ~卡片重編號 + map  ( 萬位數: 卡片類型 、 千、 百、 十位 是卡片子分類 (分類依據同一系列任務(preneed->next關係)) 、個位數在分類裡的位置   **(完成待brad確認)**~

# 畫面方面
* ~畫面多一行      **(完成待brad確認)**~

* ~輸贏的結束畫面   **(完成待littleCube確認)**~

# Bug Fixer
* "敵方上回合的行動是None"   **(完成待littleCube確認)**
* 重新連線的時候，舊狀態要清空(restart)    **(完成待littleCube確認)**
* spike傷害計算不到

# 未來:
* 其他任務導入
* 精靈導入
* 基本教程
* 排版需改進(尤其是呈現message)
* 抽卡流程跟機制設計
* 連線機制??

**Comment by brad1024** [comment]
完成: 
放棄任務
"敵方上回合的行動是None"
重新連線的時候，舊狀態要清空(restart)
輸贏的結束畫面-->直接清空畫面

新增
bug: spike的傷害計算不到

**Comment by littleCube2019** [comment]
> 完成:
> 放棄任務
> "敵方上回合的行動是None"
> 重新連線的時候，舊狀態要清空(restart)
> 輸贏的結束畫面-->直接清空畫面
> 
> 新增
> bug: spike的傷害計算不到

記得commit到自己雲端，然後告一段落可以pull request

**Comment by littleCube2019** [comment]
# 更動內容
卡片重編號
# 進度
以目前卡片來說全部完成
# 具體內容
1. 於server.js中新增missionIdToIndex的object, 
可以將missionIdToIndex[missionId] = arrayIndex
比如 missionIdToIndex[10031] = 8    表示第10000號任務卡是在"mission"這個array中第8號位置
2. 於card.js中重編號mission卡牌(照上述規則) ， 同時也將道具卡卡號拓展至萬位
並且，道具卡目前覺得可以照原案直接取餘數得到其index

**Comment by littleCube2019** [comment]
# 更動內容
message多一行
# 進度
修改完成
# 具體內容
把所有大小單位從px改成%

**Comment by brad1024** [comment]
### 傳不上去啊寫程式大師

**Comment by brad1024** [comment]
> # 實作功能
> * 道具功能
> * 選卡 (含顯示)
> * 放棄任務    **(完成待brad確認)**
> * 卡片重編號 + map  ( 萬位數: 卡片類型 、 千、 百、 十位 是卡片子分類 (分類依據同一系列任務(preneed->next關係)) 、個位數在分類裡的位置   ~~**(完成待brad確認)**~~
> 
> # 畫面方面
> * 畫面多一行      **(完成待brad確認)**
> * 輸贏的結束畫面   **(完成待littleCube確認)**
> 
> # Bug Fixer
> * "敵方上回合的行動是None"   **(完成待littleCube確認)**
> * 重新連線的時候，舊狀態要清空(restart)    **(完成待littleCube確認)**
> * spike傷害計算不到
> 
> # 未來:
> * 其他任務導入
> * 精靈導入
> * 基本教程
> * 排版需改進(尤其是呈現message)
> * 抽卡流程跟機制設計
> * 連線機制??

**Comment by brad1024** [comment]
> # 實作功能
> * 道具功能
> * 選卡 (含顯示)
> * 放棄任務    **(完成待brad確認)**
> * ~卡片重編號 + map  ( 萬位數: 卡片類型 、 千、 百、 十位 是卡片子分類 (分類依據同一系列任務(preneed->next關係)) 、個位數在分類裡的位置   **(完成待brad確認)**~
> 
> # 畫面方面
> * 畫面多一行      **(~~完成待brad確認~~)**
> * 輸贏的結束畫面   **(完成待littleCube確認)**
> 
> # Bug Fixer
> * "敵方上回合的行動是None"   **(完成待littleCube確認)**
> * 重新連線的時候，舊狀態要清空(restart)    **(完成待littleCube確認)**
> * spike傷害計算不到
> 
> # 未來:
> * 其他任務導入
> * 精靈導入
> * 基本教程
> * 排版需改進(尤其是呈現message)
> * 抽卡流程跟機制設計
> * 連線機制??

**Comment by brad1024** [comment]
> # 實作功能
> * 道具功能
> * 選卡 (含顯示)
> * 放棄任務    **(完成待brad確認)**
> * ~卡片重編號 + map  ( 萬位數: 卡片類型 、 千、 百、 十位 是卡片子分類 (分類依據同一系列任務(preneed->next關係)) 、個位數在分類裡的位置   **(完成待brad確認)**~
> 
> # 畫面方面
> * 畫面多一行      **(~完成待brad確認~)**
> * 輸贏的結束畫面   **(完成待littleCube確認)**
> 
> # Bug Fixer
> * "敵方上回合的行動是None"   **(完成待littleCube確認)**
> * 重新連線的時候，舊狀態要清空(restart)    **(完成待littleCube確認)**
> * spike傷害計算不到
> 
> # 未來:
> * 其他任務導入
> * 精靈導入
> * 基本教程
> * 排版需改進(尤其是呈現message)
> * 抽卡流程跟機制設計
> * 連線機制??
